ruby/config/routes.rb
Rails.application.routes.draw do

  get 'bugs' => 'bug#index', as: 'bugs'
  get 'bug/:id' => 'bug#show', as: 'bug'
  get 'create' => 'bug#create', as: 'create_bug'
  post 'create' => 'bug#new', as: 'send_bug'

  get 'login' => 'sessions#new', as: 'login'
  root 'sessions#new'
  post 'login' => 'sessions#connect'
  delete 'logout' => 'sessions#logout', as: 'logout'

end

ruby/app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :user


  scope :open, -> { where(state:0) }
  scope :assigned, -> { where(state:1) }
  scope :closed, -> { where(state:2) }
end

ruby/app/models/user.rb
class User < ActiveRecord::Base
  has_many :bugs
  has_and_belongs_to_many :user
  validates :username,
    presence: true,
    length: {minimun: 6, maximum: 50},
    uniqueness: true
  has_secure_password
  validates :password, presence:true, length: { minimum:6, maximum:255 }
end

ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  protected
  def confirm_logged_in
    if !session[:user_id]
      redirect_to login_path
      return false
    else
      return true
    end
  end
end

ruby/app/controllers/bug_controller.rb
class BugController < ApplicationController
  before_action :confirm_logged_in
  def index
    @bugs = Bug.all
  end
  def new
    puts params
    bug = Bug.create title: params[:bug][:title],
      description: params[:bug][:description],
      owner_id: current_user.id,
      state: 0
    bug.user << User.find(params[:bug][:assigned_to])
    redirect_to bugs_path
  end
  def create
    @users = User.all
  end
  def show
    @bug = Bug.find(params[:id])
    @owner = User.find(@bug.owner_id)
  end
end

ruby/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

ruby/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def connect
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to bugs_path
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end
  def logout
    log_out
    redirect_to login_path
  end
end

ruby/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/helpers/bug_helper.rb
module BugHelper
end

ruby/app/helpers/pages_helper.rb
module PagesHelper
end

ruby/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

ruby/app/helpers/user_helper.rb
module UserHelper
end

ruby/app/views/bug/create.html.erb
<h1> Report a bug </h1>
<%= form_for(:bug, url:send_bug_path) do |f| %>
  <p>
  <h3>
    <%= f.label :title %>
  </h3>
  <%= f.text_field :title, :required => true %>
  </p>
  <p>
  <h3>
    <%= f.label :description %>
  </h3>
  <%= f.text_area :description, :required => true %>
  </p>
  <p>
  <h3>
    <%= f.label :assignement %>
  </h3>
  </p>
  <p>
  <%= f.select :assigned_to, options_from_collection_for_select(@users, "id", "username") %>
  </p>
  <%= f.submit "create bug" %>
<% end %>

ruby/app/views/bug/index.html.erb
<div> Known bug </div>
<ul>
<% @bugs.each do |bug| %>
  <li>
  <div>
    <h2> <%= link_to bug.title, bug_path(bug.id) %> </h2>
    <% bug.user.each do |us| %>
      <h4> assigned to :<%= us.username %></h4>
    <% end %>
    <p> <%= bug.description %></p>
  </div>
  </li>
<% end %>
</ul>

ruby/app/views/bug/show.html.erb
<a href="/bugs"> return </a>
<h1> <%= @bug.title %> </h1>
<h2> owner : <%= @owner.username %> </h2>
<p>  <%= @bug.description %> </p>

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SiteBug</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to :create, create_bug_path() %>
	<%= link_to :index, bugs_path() %>
	<%= link_to :logout, logout_path(), method: :delete %>
	<%= yield %>

</body>
</html>

ruby/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

ruby/app/views/user/index.html.erb
<% @users.each do |user| %>
  <p> <%= user.username %>
<% end %>